# Generated by Django 3.0.1 on 2020-10-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201027_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='sec1_total',
            new_name='Logical',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='sec2_total',
            new_name='Verabal',
        ),
    ]
