# Generated by Django 3.0.1 on 2020-10-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201028_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='Verabal',
            new_name='Verbal',
        ),
    ]
