# Generated by Django 3.1.1 on 2021-02-18 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_spatial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantitative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('la', models.CharField(max_length=500)),
                ('lb', models.CharField(max_length=500)),
                ('lc', models.CharField(max_length=500)),
                ('ld', models.CharField(max_length=500)),
                ('ans', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='Quantitative',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='result',
            name='Spatial',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='spatial',
            name='ans',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
